### ISSUE TITLE
tries to concat None to a string while building DM tree

### ISSUE THREAD

**Issue by Vosjedev** [mzivic7/endcord#14]
**Describe the bug**
From what I can tell from the stacktrace, endcord tries to concatenate a None to a string while building the DMlist. It happened on startup this time, but I've seen it happen during runtime on previous commits too. I'll try to get more information about the specific situation causing this in a few hours.
Full stacktrace:
```python
Traceback (most recent call last):
  File "main.py", line 122, in <module>
    main(args)
    ~~~~^^^^^^
  File "main.py", line 111, in main
    curses.wrapper(app.Endcord, config, keybindings)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "curses/__init__.py", line 94, in wrapper
  File "endcord/app.py", line 200, in __init__
    self.main()
    ~~~~~~~~~^^
  File "endcord/app.py", line 4881, in main
    self.switch_channel(channel_id, channel_name, guild_id, guild_name, open_member_list=self.member_list_auto_open)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "endcord/app.py", line 501, in switch_channel
    self.set_seen(channel_id)
    ~~~~~~~~~~~~~^^^^^^^^^^^^
  File "endcord/app.py", line 4196, in set_seen
    self.update_tree()
    ~~~~~~~~~~~~~~~~^^
  File "endcord/app.py", line 4131, in update_tree
    self.tree, self.tree_format, self.tree_metadata = formatter.generate_tree(
                                                      ~~~~~~~~~~~~~~~~~~~~~~~^
        self.dms,
        ^^^^^^^^^
    ...<18 lines>...
        show_invisible = self.config["tree_show_invisible"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "endcord/formatter.py", line 1909, in generate_tree
    name = dm_status_char + name
           ~~~~~~~~~~~~~~~^~~~~~
TypeError: can only concatenate str (not "NoneType") to str
[PYI-6871:ERROR] Failed to execute script 'main' due to unhandled exception!
```

**Environment (please complete the following information):**
 - Platform: linux aarch64
 - OS: danctnix linux, python 3.13.3
 - Terminal: Konsole
 - Version: commit 5d123b4

**To Reproduce**
*to be done, it happened on startup for me*

**Expected behavior**
I expected the application to not crash :).

**Additional context**
For now, this is all the information I can give. I'll update once I know more.

**Comment by sparklost** [comment]
Some of your DMs or group DMs has weird name, probably unnamed group DM with only one member (owner - you). 
I fixed that in new commit, and added safety check that will set name to "Unknown DM" instead crashing.

Let me know it there are no "Unknown DM"s so I can close this issue.

But if there are:
Identify which DM it is and find its actual name in official client.
Then open file `./endcord/gateway.py` and after [this](https://github.com/mzivic7/endcord/blob/4c4a4897807942ccf6157809699aaccdfaa5c755/endcord/gateway.py#L436) line, paste this:
```py
debug.save_json(data["private_channels"], "dms.json", False)
debug.save_json(data["users"], "users.json", False)
```
And run endcord from source, 2 json files will be saved in project root, its better to **not send them** because they contain sensitive data like usernames, notes, pfps, IDs...

So you'll have to search for that DM:
in official discord: right click on DM and "Copy Channel ID"
Open `dms.json` and search for this ID, `name` is probably `None`. 
What `type` is it?
Are there any IDs in in `recipient_ids` or its empty list (`recipient_ids: []`)?
If there are IDs: copy first one, and open `users.json`, search for ID, look if this user has `global_name` and `username`.

**Comment by Vosjedev** [comment]
I found 3 of them:

1. Amount of recipients listed is 3, all have a username and global_name. Type is 3. Name of the group is indeed `null`.
2. Amount of recipients listed is 1, has a username and global name. Type is 3. Name of the group is once again `null`.
3. Amount of recipients listed is 3, all have username and global name. Type is 3. Name of group is again `null`.
4. Amount of recipients listed is 1, has a username and global name. Type is 3. Name of the group is once again `null`.

While `find`ing through the json for `"type": 3`, I noticed all these groups have something in common that other unaffected groups don't have: `name` is `null`. Maybe something is broken in generating a name when `name` is `null` for type 3?

**Comment by sparklost** [comment]
This means all these groups are unnamed, so they should appear as `[username]'s Group` in official client.
Can you also check `owner_id` for these DMs, copy ID and search for it in `users.json`.

**Comment by Vosjedev** [comment]
Still the same: `owner_id` has a username and global name on all of them...
Although I do have to say, the official client lists all the members separated by `, ` instead of the format you mentioned as the names for these groups.

**Comment by Vosjedev** [comment]
I think I got the bug. The check on line 448 always succeeds for groups DMs, even if `dm["name"]` is None. `name` is (as far as I could tell) always a present field in the json for groups, except it's `null` when no name is set. The result is that the checks after that never run, of course.

Changing the line to be
```python
                        if "name" in dm and dm["name"]:   # for group dm
```
makes it work successfully.

------

By the way, as a sidenote, consider using something like
```python
name=", ".join((
      r["global_name"]
      if "global_name" in r else
      r["username"] for r in recipients
    ))
```
to make the group name a list of members (helping in identifying which group it is). Fully up to you what you do with that though.

**Comment by sparklost** [comment]
Yes that's it, thanks.
And I made it include all group participants names, with slight modification to show owners name first.

**Comment by Vosjedev** [comment]
No problem, thanks!
